#! The only purposes of this file is to silent the flake8 errors /warning
#! since I got the flak8 extension in vscode, is very noisy. only purposes of the file
#! because we are not suing flak8 in this project
[flake8]
ignore =
    E501,  # Line too long (conflicts with Black)
